#!/bin/ksh
#############################################################################
# daily_pos_sales.ksh
# Deployed script for graph mp/daily_pos_sales.mp
# Generated by Ab Initio GDE, hand-maintained thereafter.
#
# Co>Operating System entry point invoked by the nightly plan.
# Usage: daily_pos_sales.ksh <BUSINESS_DATE:YYYYMMDD>
#############################################################################

set -e
set -o pipefail

: ${AB_HOME:?"AB_HOME not set - source config/abinitio.env first"}
: ${PROJECT_DIR:?"PROJECT_DIR not set - source sand/project.pset first"}

export PATH=$AB_HOME/bin:$PATH

BUSINESS_DATE=${1:?"usage: daily_pos_sales.ksh <YYYYMMDD>"}
export BUSINESS_DATE

. $PROJECT_DIR/sand/sandbox.pset
. $PROJECT_DIR/dbc/edw.dbc.env

AI_SERIAL=$PROJECT_DIR/data/serial
POS_INPUT_FILE=$PROJECT_DIR/data/in/pos_sales_${BUSINESS_DATE}.dat
PRODUCT_DIM_FILE=$AI_SERIAL/product_dim.dat
STORE_DIM_FILE=$AI_SERIAL/store_dim.dat
SUMMARY_OUT_FILE=$PROJECT_DIR/data/out/daily_sales_summary_${BUSINESS_DATE}.dat
REJECT_OUT_FILE=$PROJECT_DIR/data/out/reject_${BUSINESS_DATE}.dat

echo "[$(date '+%Y-%m-%d %H:%M:%S')] START daily_pos_sales BUSINESS_DATE=$BUSINESS_DATE"

#---------------------------------------------------------------------------
# 1. Cleanse raw POS lines  (REFORMAT cleanse + select is_valid_line)
#---------------------------------------------------------------------------
m_dump $PROJECT_DIR/dml/pos_sales.dml $POS_INPUT_FILE \
  | m_eval "$PROJECT_DIR/xfr/pos_sales_cleanse.xfr" \
  > $AI_SERIAL/cleansed_${BUSINESS_DATE}.dat

#---------------------------------------------------------------------------
# 2. Sort on join key (upc), JOIN to product + store dimensions
#---------------------------------------------------------------------------
m_sort -key upc $AI_SERIAL/cleansed_${BUSINESS_DATE}.dat \
  > $AI_SERIAL/cleansed_sorted_${BUSINESS_DATE}.dat

m_join \
  -input0 $AI_SERIAL/cleansed_sorted_${BUSINESS_DATE}.dat -key0 upc \
  -input1 $PRODUCT_DIM_FILE                               -key1 upc \
  -input2 $STORE_DIM_FILE                                 -key2 store_id \
  -join-type inner \
  -transform $PROJECT_DIR/xfr/dim_join.xfr \
  -unused0 $REJECT_OUT_FILE \
  > $AI_SERIAL/joined_${BUSINESS_DATE}.dat

#---------------------------------------------------------------------------
# 3. Sort on rollup key, ROLLUP to daily grain
#---------------------------------------------------------------------------
m_sort -key "business_date store_id department category" \
  $AI_SERIAL/joined_${BUSINESS_DATE}.dat \
  > $AI_SERIAL/joined_sorted_${BUSINESS_DATE}.dat

m_rollup \
  -key "business_date store_id department category" \
  -transform $PROJECT_DIR/xfr/sales_rollup.xfr \
  $AI_SERIAL/joined_sorted_${BUSINESS_DATE}.dat \
  > $SUMMARY_OUT_FILE

#---------------------------------------------------------------------------
# 4. Load target table EDW.F_DAILY_SALES_SUMMARY
#---------------------------------------------------------------------------
m_db load $PROJECT_DIR/dbc/edw.dbc \
  -table EDW.F_DAILY_SALES_SUMMARY \
  -input $SUMMARY_OUT_FILE \
  -record-format $PROJECT_DIR/dml/daily_sales_summary.dml \
  -mode append

REJECT_ROWS=$(m_wc -l $REJECT_OUT_FILE 2>/dev/null | awk '{print $1}')
echo "[$(date '+%Y-%m-%d %H:%M:%S')] rejected (unmatched UPC) rows: ${REJECT_ROWS:-0}"
echo "[$(date '+%Y-%m-%d %H:%M:%S')] END   daily_pos_sales BUSINESS_DATE=$BUSINESS_DATE"
